### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by kaszuster** [vrondakis/zap-jenkins-pipeline-plugin#1]
Hi Manolis,

id like to know about the status of the project. Right now i am trying to port a project of mine from traditional Jenkins configuration to Pipeline, running ZAP is one of the tasks i have to solve. I have found your repo by  coincidence and it seems to solve some problems of mine. 

Id like to know:
- is it or will it be useable in Jenkins
- does it start the ZAP Server (startZap seems to have some issues or isnt finished yet)
- does it run the attack
- does it shut down the Server at the end of the build
- is there any type of schedule :D?

I havent worked on Jenkins Plugins yet, but maybe i can give you a hand.

**Comment by vrondakis** [comment]
Hey, if you want to try the plugin out you will just need to build it, you can just run _mvn install_ at the root, which will generate a HPI file for jenkins.

I had the line to actually start ZAP commented out by mistake, so that's why (if you tried) it wasn't starting 😢, get the latest version for a quick fix

To run an attack you can call runZapAttack(), it will start attacks on the hosts you provide in allowedHosts (in startZap), and localhost. 

It shuts down ZAP automatically after archiveZap() has finished

What do you mean by schedule? Run zap every x? You could create a new pipeline job that calls the functions above and runs at certain times (Configure job -> Build periodically)

There is a bunch of stuff that still needs doing, eg a way to load sessions, URL lists & attack policies, ajaxSpider, more detailed reports with raw request/resposes, Windows support (easy), ect, so feel free to contribute 😄

**Comment by kaszuster** [comment]
Hey,

after some configuration and try error approache i managed to get things running. We are still missing some features to port our projekt to Jenkins Pipeline but this looks like a good starting point. I will discuss this with my colleagues and hopefully i will be able to contribute. I will let you know in a couple of days. 

By schedule i mean some kind of release plan, like any specific features you want to implement or when (if) you want to release the plugin to Jenkins Plugin repo.

**Comment by vrondakis** [comment]
Hey
What problems did you have running the plugin (so I can make it better)? It meets all of our requirements currently but I am planning on adding more features, what do you need?

I am planning on releasing this to the Jenkins plugin repo ~soon~ after I clean things up a little & add some more features (above)

**Comment by kaszuster** [comment]
Here is a short list of the problems i had and features i need:

- problems to get the configuration right because none of the exceptions (occurring in ZapDriver) are propagated to the Jenkins Output.
- some kind of integration test with a local installation of ZAP would be helpful to speed things up (i didnt want to build and install the plugin over and over again)
- Method to check if the ZAP Server is currently running (startup takes some time)
- Load an existing session
- Load a file with URLs to scan
- Change scan/attack options (path traversal on/off)

I implemented some of the things in a quick and dirty way to evaluate the possibilities but i have to get permission to keep working on it and contribute.

**Comment by vrondakis** [comment]
1. Not done, I agree it is hard to see exactly what's failing without looking in the zap log
2. This is the script I use for quickly building & installing, there are no integrations test yet.

```
sudo service jenkins stop
sudo mvn install
sudo cp ./target/zap-comp.hpi /var/lib/jenkins/plugins/
sudo service jenkins start
```
3. startZap will wait until ZAP has started before continuing & fail the build if it never goes up. The code for this is in StartZapExecution.java
4. I have added a sessionPath parameter to startZap that loads a session at the path you specify. If you want to run a scan as a specific user you can use the userId parameter in runZapAttack - eg runZapAttack(userId: 2)
5. I added importZapUrls("path/to/urls"), but you need the import urls plugin to use it

6. You can now import scan policies using importZapScanPolicy("path/to/.policy/file"). You can then run runZapAttack(scanPolicyName: "nameofpolicy") to run an attack with a specific policy. 

Do these changes help?

**Comment by vrondakis** [comment]
Closing due to no reply
